# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import compute_service_pb2 as compute__service__pb2


class ComputeServiceStub(object):
    """ComputeService - 通用计算服务
    提供远程计算能力，完全解耦具体模型实现
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/splitlearn.comm.ComputeService/Compute',
                request_serializer=compute__service__pb2.ComputeRequest.SerializeToString,
                response_deserializer=compute__service__pb2.ComputeResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/splitlearn.comm.ComputeService/HealthCheck',
                request_serializer=compute__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=compute__service__pb2.HealthResponse.FromString,
                )
        self.GetServiceInfo = channel.unary_unary(
                '/splitlearn.comm.ComputeService/GetServiceInfo',
                request_serializer=compute__service__pb2.ServiceInfoRequest.SerializeToString,
                response_deserializer=compute__service__pb2.ServiceInfoResponse.FromString,
                )


class ComputeServiceServicer(object):
    """ComputeService - 通用计算服务
    提供远程计算能力，完全解耦具体模型实现
    """

    def Compute(self, request, context):
        """执行计算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceInfo(self, request, context):
        """获取服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=compute__service__pb2.ComputeRequest.FromString,
                    response_serializer=compute__service__pb2.ComputeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=compute__service__pb2.HealthRequest.FromString,
                    response_serializer=compute__service__pb2.HealthResponse.SerializeToString,
            ),
            'GetServiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceInfo,
                    request_deserializer=compute__service__pb2.ServiceInfoRequest.FromString,
                    response_serializer=compute__service__pb2.ServiceInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearn.comm.ComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ComputeService(object):
    """ComputeService - 通用计算服务
    提供远程计算能力，完全解耦具体模型实现
    """

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splitlearn.comm.ComputeService/Compute',
            compute__service__pb2.ComputeRequest.SerializeToString,
            compute__service__pb2.ComputeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splitlearn.comm.ComputeService/HealthCheck',
            compute__service__pb2.HealthRequest.SerializeToString,
            compute__service__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/splitlearn.comm.ComputeService/GetServiceInfo',
            compute__service__pb2.ServiceInfoRequest.SerializeToString,
            compute__service__pb2.ServiceInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
