# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import compute_service_pb2 as compute__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in compute_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputeServiceStub(object):
    """ComputeService - 通用计算服务
    提供远程计算能力，完全解耦具体模型实现
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/splitlearn.comm.ComputeService/Compute',
                request_serializer=compute__service__pb2.ComputeRequest.SerializeToString,
                response_deserializer=compute__service__pb2.ComputeResponse.FromString,
                _registered_method=True)
        self.ComputeBackward = channel.unary_unary(
                '/splitlearn.comm.ComputeService/ComputeBackward',
                request_serializer=compute__service__pb2.BackwardRequest.SerializeToString,
                response_deserializer=compute__service__pb2.BackwardResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/splitlearn.comm.ComputeService/HealthCheck',
                request_serializer=compute__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=compute__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetServiceInfo = channel.unary_unary(
                '/splitlearn.comm.ComputeService/GetServiceInfo',
                request_serializer=compute__service__pb2.ServiceInfoRequest.SerializeToString,
                response_deserializer=compute__service__pb2.ServiceInfoResponse.FromString,
                _registered_method=True)
        self.StreamMonitoring = channel.unary_stream(
                '/splitlearn.comm.ComputeService/StreamMonitoring',
                request_serializer=compute__service__pb2.MonitoringStreamRequest.SerializeToString,
                response_deserializer=compute__service__pb2.MonitoringSnapshotResponse.FromString,
                _registered_method=True)


class ComputeServiceServicer(object):
    """ComputeService - 通用计算服务
    提供远程计算能力，完全解耦具体模型实现
    """

    def Compute(self, request, context):
        """执行计算（前向传播）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeBackward(self, request, context):
        """反向传播计算
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceInfo(self, request, context):
        """获取服务信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMonitoring(self, request, context):
        """实时监控流（服务端定期推送资源快照）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=compute__service__pb2.ComputeRequest.FromString,
                    response_serializer=compute__service__pb2.ComputeResponse.SerializeToString,
            ),
            'ComputeBackward': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeBackward,
                    request_deserializer=compute__service__pb2.BackwardRequest.FromString,
                    response_serializer=compute__service__pb2.BackwardResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=compute__service__pb2.HealthRequest.FromString,
                    response_serializer=compute__service__pb2.HealthResponse.SerializeToString,
            ),
            'GetServiceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceInfo,
                    request_deserializer=compute__service__pb2.ServiceInfoRequest.FromString,
                    response_serializer=compute__service__pb2.ServiceInfoResponse.SerializeToString,
            ),
            'StreamMonitoring': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMonitoring,
                    request_deserializer=compute__service__pb2.MonitoringStreamRequest.FromString,
                    response_serializer=compute__service__pb2.MonitoringSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearn.comm.ComputeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearn.comm.ComputeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputeService(object):
    """ComputeService - 通用计算服务
    提供远程计算能力，完全解耦具体模型实现
    """

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearn.comm.ComputeService/Compute',
            compute__service__pb2.ComputeRequest.SerializeToString,
            compute__service__pb2.ComputeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeBackward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearn.comm.ComputeService/ComputeBackward',
            compute__service__pb2.BackwardRequest.SerializeToString,
            compute__service__pb2.BackwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearn.comm.ComputeService/HealthCheck',
            compute__service__pb2.HealthRequest.SerializeToString,
            compute__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearn.comm.ComputeService/GetServiceInfo',
            compute__service__pb2.ServiceInfoRequest.SerializeToString,
            compute__service__pb2.ServiceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMonitoring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/splitlearn.comm.ComputeService/StreamMonitoring',
            compute__service__pb2.MonitoringStreamRequest.SerializeToString,
            compute__service__pb2.MonitoringSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
